@startuml

hide footbox
skinparam sequenceReferenceBackgroundColor #f7807c

participant ":AddItemCommand" as AddItemCommand #E0BBE4
participant "newItem:Item" as newItem #95E1D3
participant ":ItemMap" as ItemMap #F9FBCB
participant ":TreeSet" as TreeSet #A0D8D1
participant "oldItem:Item" as oldItem #95E1D3
participant ":Storage" as Storage #FFABAB

-> AddItemCommand : execute(items, storage)
activate AddItemCommand

AddItemCommand -> newItem : newItem(itemName, quantity, expiryDate)
activate newItem
return item
deactivate newItem

AddItemCommand -> ItemMap : addItem(item)
activate ItemMap

ItemMap -> newItem : <<get attributes>>
activate newItem
return <<attributes>>
deactivate newItem

alt item with same name exists
    ItemMap -> TreeSet : get(name)
    activate TreeSet
    return itemSet

    loop until item with same expiry date \nis found or end of array is reached
        opt item has same expiry date
            ItemMap -> oldItem : setQuantity(newQuantity)
            activate oldItem
            return
            deactivate oldItem
        end
    end

    opt item with same expiry \ndate not found
        ItemMap -> TreeSet : add(item)
        activate TreeSet
        return
        deactivate TreeSet
    end


else else
    ItemMap -> TreeSet : TreeSet<>()
    activate TreeSet
    return itemSet
    deactivate TreeSet
    ItemMap -> TreeSet : add(item)
    activate TreeSet
    return
    deactivate TreeSet
    ItemMap -> ItemMap : put(name, itemSet)
    activate ItemMap
    return
    ||10||
end

ItemMap --> AddItemCommand
deactivate ItemMap

AddItemCommand -> Storage : saveItem(item)
activate Storage
||||||
return
deactivate Storage

<-- AddItemCommand
deactivate AddItemCommand
destroy AddItemCommand

@enduml