@startuml

skinparam classAttributeIconSize 0
hide circles

class ItemMap {
    + addItem(newItem: Item)
    + deleteItem(name: String, expiryDate: Optional<LocalDate>)
    + editItem(updatedItem: Item)
    + listItems()
    + listExpiringItems()
    + listToRestock()
    + findItem(itemName: String) : ItemMap
    + getExpiringItems(itemName: String) : ItemMap
}

ItemMap "1" *-- "1" Map : contains >

interface Map << interface >> {
    itemName: String
    item: TreeSet<Item>
}

note right of Map : Maps key(itemName) to value(item)\nHas any amount of key-value pairs
note bottom of Map : Stored as a Map, intialised as a LinkedHashMap

@enduml