@startuml

skinparam classAttributeIconSize 0
hide circles

interface Comparable<Item> << interface >>
Comparable <|-[dashed]- Item

class Item {
    - name: String
    - quantity: int = 1
    - expiryDate: Optional<LocalDate>

    + getName() : String
    + getQuantity() : int
    + getExpiryDate() : Optional<LocalDate>
    + compareTo(other: Item) : int
}

note right of Item : quantity defaults to 1 if not specified
note bottom of Item : Item compares to other \nItems based on expiryDate

@enduml